"""Initial schema

Revision ID: 92794303a08e
Revises: 
Create Date: 2025-11-30 00:52:04.064427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92794303a08e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('broad_category', sa.String(length=50), nullable=True),
    sa.Column('icon', sa.String(length=10), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('temp_uploads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('transaction_count', sa.Integer(), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_expires', 'temp_uploads', ['expires_at'], unique=False)
    op.create_table('upload_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('saved_at', sa.DateTime(), nullable=True),
    sa.Column('new_transactions', sa.Integer(), nullable=True),
    sa.Column('duplicate_transactions', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_status', 'upload_history', ['status'], unique=False)
    op.create_index('idx_uploaded_at', 'upload_history', ['uploaded_at'], unique=False)
    op.create_table('merchants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('normalized_name', sa.String(length=200), nullable=True),
    sa.Column('default_category_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['default_category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('bank_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('merchant_id', sa.Integer(), nullable=True),
    sa.Column('account_number', sa.String(length=50), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('cheque_no', sa.String(length=50), nullable=True),
    sa.Column('value_date', sa.Date(), nullable=True),
    sa.Column('source_file', sa.String(length=255), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'amount', 'description', 'bank_id', name='uq_transaction')
    )
    op.create_index('idx_bank', 'transactions', ['bank_id'], unique=False)
    op.create_index('idx_category', 'transactions', ['category_id'], unique=False)
    op.create_index('idx_date', 'transactions', ['date'], unique=False)
    op.create_index('idx_merchant', 'transactions', ['merchant_id'], unique=False)
    op.create_index('idx_type', 'transactions', ['type'], unique=False)
    op.create_index('idx_year', 'transactions', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_year', table_name='transactions')
    op.drop_index('idx_type', table_name='transactions')
    op.drop_index('idx_merchant', table_name='transactions')
    op.drop_index('idx_date', table_name='transactions')
    op.drop_index('idx_category', table_name='transactions')
    op.drop_index('idx_bank', table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('merchants')
    op.drop_index('idx_uploaded_at', table_name='upload_history')
    op.drop_index('idx_status', table_name='upload_history')
    op.drop_table('upload_history')
    op.drop_index('idx_expires', table_name='temp_uploads')
    op.drop_table('temp_uploads')
    op.drop_table('categories')
    op.drop_table('banks')
    # ### end Alembic commands ###
